version: '3.4'
services:
  consul:
    image: consul:1.5.2
    ports:
      - 8500:8500
  potato1:
    hostname: potato1
    build: .
    ports:
      - 8001:6000
    command: ["agent"]
    depends_on:
      - consul
  potato2:
    hostname: potato2
    build: .
    command: ["agent"]
    ports:
      - 8002:6000
    depends_on:
      - consul
  potato3:
    hostname: potato3
    build: .
    command: ["agent"]
    ports:
      - 8003:6000
    depends_on:
      - consul
 