version: '3.4'
services:
  consul:
    image: consul:1.5.2
    ports:
      - 8500:8500
  potato1:
    hostname: potato1
    build: .
    command: ["server"]
    depends_on:
      - consul
  potato2:
    hostname: potato2
    build: .
    command: ["server"]
    depends_on:
      - consul
  potato3:
    hostname: potato3
    build: .
    command: ["server"]
    depends_on:
      - consul
  potato4:
    hostname: potato4
    build: .
    command: ["server"]
    depends_on:
      - consul
  potato4:
    hostname: potato4
    build: .
    command: ["server"]
    depends_on:
      - consul